export const mockDataMeals = {
  meals: [
    {
      idMeal: '52860',
      strMeal: 'Chocolate Raspberry Brownies',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'American',
      strInstructions:
      `Heat oven to 180C/160C fan/gas 4. Line a 20 x 30cm 
      baking tray tin with baking parchment.
      Put the chocolate, butter and sugar in a pan and gently melt, 
      stirring occasionally with a wooden spoon. 
      Remove from the heat.\r\nStir the eggs, one by one, 
      into the melted chocolate mixture. Sieve over the 
      flour and cocoa, and stir in. Stir in half the 
      raspberries, scrape into the tray, then scatter 
      over the remaining raspberries. Bake on 
      the middle shelf for 30 mins or, if you 
      prefer a firmer texture, for 5 mins more. 
      Cool before slicing into squares. 
      Store in an airtight container for up to 3 days.`,
      strMealThumb: 'https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg',
      strTags: 'Chocolate,Desert,Snack',
      strYoutube: 'https://www.youtube.com/watch?v=Pi89PqsAaAg',
      strIngredient1: 'Dark Chocolate',
      strIngredient2: 'Milk Chocolate',
      strIngredient3: 'Salted Butter',
      strIngredient4: 'Light Brown Soft Sugar',
      strIngredient5: 'Eggs',
      strIngredient6: 'Plain Flour',
      strIngredient7: 'Cocoa',
      strIngredient8: 'Raspberries',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '200g',
      strMeasure2: '100g ',
      strMeasure3: '250g',
      strMeasure4: '400g',
      strMeasure5: '4 large',
      strMeasure6: '140g',
      strMeasure7: '50g',
      strMeasure8: '200g',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/2121648/bestever-chocolate-raspberry-brownies',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const mockDataDrinks = {
  drinks: [
    {
      idDrink: '178319',
      strDrink: 'Aquamarine',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake well in a shaker with ice.\r\nStrain in a martini glass.',
      strInstructionsES:
      'Agite bien en una coctelera con hielo. Cuela en una copa de Martini.',
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT:
      'Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg',
      strIngredient1: 'Hpnotiq',
      strIngredient2: 'Pineapple Juice',
      strIngredient3: 'Banana Liqueur',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz',
      strMeasure2: '1 oz',
      strMeasure3: '1 oz',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
  ],
};

export const mockDataMealsCategories = {
  meals: [
    { strCategory: 'Beef' },
    { strCategory: 'Breakfast' },
    { strCategory: 'Chicken' },
    { strCategory: 'Dessert' },
    { strCategory: 'Goat' },
    { strCategory: 'Lamb' },
    { strCategory: 'Miscellaneous' },
    { strCategory: 'Pasta' },
    { strCategory: 'Pork' },
    { strCategory: 'Seafood' },
    { strCategory: 'Side' },
    { strCategory: 'Starter' },
    { strCategory: 'Vegan' },
    { strCategory: 'Vegetarian' },
  ],
};

export const mockDataDrinksCategories = {
  drinks: [
    { strCategory: 'Ordinary Drink' },
    { strCategory: 'Cocktail' },
    { strCategory: 'Shake' },
    { strCategory: 'Other \\/ Unknown' },
    { strCategory: 'Cocoa' },
    { strCategory: 'Shot' },
    { strCategory: 'Coffee \\/ Tea' },
    { strCategory: 'Homemade Liqueur' },
    { strCategory: 'Punch \\/ Party Drink' },
    { strCategory: 'Beer' },
    { strCategory: 'Soft Drink' },
  ],
};
